language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}

script:
  - composer install --no-dev
  - vendor/bin/phpunit

env:
  - PHPUNIT_VERSION=4.8.*

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_VERSION=4.8.*
    - php: 7.0
      env: PHPUNIT_VERSION=5.4.*
