language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - rm composer.lock
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}

script:
  - composer install --no-dev
  - vendor/bin/phpunit

env:
  - PHPUNIT_VERSION=5.4.*

php:
  - 7.0
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      env: PHPUNIT_VERSION=4.8.*
    - php: 5.6
      env: PHPUNIT_VERSION=4.8.*
